# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- alpine

resources:
- repo: self

stages:
- stage: Build
  displayName: Build and Push ClamAV
  jobs:  
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(Build.SourceBranchName)$(_DASH)$(Build.SourceVersion)
          latest
    - task: Docker@2
      displayName: 'Master/DEV - Push Docker Image to ACR'
      inputs:
        containerRegistry: 'scACR-F2'
        repository: 'clamav'
        command: 'push'
        tags: |
          $(Build.SourceBranchName)$(_DASH)$(Build.SourceVersion)
          latest
